CREATE DATABASE CAB_Manage; 
CREATE TABLE Vehicle (
CAR_ID VARCHAR(10),
MODEL VARCHAR(25),
PLATE_NUMBER VARCHAR(15),
COLOR VARCHAR(15),
HIRE_DATE DATE,
AVAILABILITY BOOLEAN);
SELECT * FROM VEHICLES;

ALTER TABLE VEHICLES
MODIFY COLUMN CAR_ID INT(25);

RENAME DATABASE CAB_Manage TO CAB_MANAGE;
ALTER TABLE VEHICLES
DROP COLUMN HIRE_DATE;

ALTER TABLE VEHICLES
MODIFY COLUMN CAR_ID TO CAR_ID INT(10) PRIMARY KEY AUTO_INCREMENT;
MODIFY AVAIL

CREATE TABLE Driver (
DRIVER_ID VARCHAR (10),
DRIVER_NAME VARCHAR(50),
CONTACT_NUMBER VARCHAR(10),
DRIVER_AVAILABILITY BOOLEAN,
DRIVER_JOIN DATE
);

SELECT * FROM Driver;

ALTER TABLE Driver
MODIFY COLUMN DRIVER_ID INT(10) PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE Vehicles
RENAME HIRE_DATE TO CAR_JOIN_DATE;
MODIFY COLUMN CAR_ID INT(10) PRIMARY KEY AUTO_INCREMENT;

CREATE TABLE CUSTOMER (
CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(50),
CUSTOMER_PHONE VARCHAR(11),
CUSTOMER_LOCATION VARCHAR(25),
CUSTOMER_DESTINATION VARCHAR(25)
);
SELECT * FROM CUSTOMER;


CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INT,
DRIVER_ID INT,
CAR_ID INT,
ORDER_DATE DATE,
FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (DRIVER_ID)
	REFERENCES Driver(DRIVER_ID),
FOREIGN KEY (CAR_ID)
	REFERENCES Vehicles(CAR_ID)
);
SELECT * FROM ORDERS;

CREATE TABLE ADMINS (
ADMINS_ID INT PRIMARY KEY AUTO_INCREMENT,
ADMIN_NAME VARCHAR(50),
ADMIN_PHONE VARCHAR(11)
);
SELECT * FROM ADMINS;


